@startuml
object guest_example {
    guestID = "G711"
    name = "Bob"
    group = "Reception"
    sensitiveInfo = "Bob's Schedule"
    permissionLevel = 1
}

object badge_example {
    badgeID = "B007"
    guestName = "Bob"
    guestID = "G711"
    status = "Generated"
}

object permission_example {
    level = 1
    description = "High Access"
}

object vehicle_example {
    vehicleID = "苏A88888"
    availability = true
    schedule = ["2024-11-01 10:00:00-2024-11-01 14:00:00", "2024-11-01 18:00:00-2024-11-01 20:00:00"]
}

object auditLog_example {
    logID = "L001"
    action = "Created Badge B007 G711"
    timestamp = "2024-11-01 10:00:00"

    logID = "L002"
    action = "Requested Vehicle G711 苏A88888"
    timestamp = "2024-11-01 15:00:00"
}

object security_example {
    // Security methods and attributes can be represented if in need
}

object backup_example {
    // Backup methods and attributes can be represented if in need
}


guest_example --* badge_example : 拥有
guest_example --* permission_example : 拥有
guest_example --> vehicle_example : 请求使用
auditLog_example --o guest_example : 记录
auditLog_example --o badge_example : 记录
auditLog_example --o vehicle_example : 记录
auditLog_example --o security_example : 记录
auditLog_example --o backup_example : 记录
@enduml
